# Generated by Django 4.1.4 on 2023-04-08 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusub',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.submenu'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.menu'),
        ),
    ]
